/**
 * Datos de imagenes de la pagina de bautizos (slider + galeria).
 *
 * Separados del componente (Single Responsibility): las rutas de imagenes son
 * datos, no logica de presentacion. Cambian por una razon distinta (Dan agrega
 * fotos) que la logica del componente.
 */

export interface GalleryThumb {
  src: string;
  orientation: 'v' | 'h';
}

export const BAUTIZOS_SLIDER_IMAGES: string[] = [
    'assets/images/bautizos/slider/BAUTIZO-001.jpg',
    'assets/images/bautizos/slider/BAUTIZO-005.jpg',
    'assets/images/bautizos/slider/BAUTIZO-029.jpg',
    'assets/images/bautizos/slider/BAUTIZO-015.jpg',
    'assets/images/bautizos/slider/BAUTIZO-020.jpg',
];

export const BAUTIZOS_GALLERY_IMAGES: GalleryThumb[] = [
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-001.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-002.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-003.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-004.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-005.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-006.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-007.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-008.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-009.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-011.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-012.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-013.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-014.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-015.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-016.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-017.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-018.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-019.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-020.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-021.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-022.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-023.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-025.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-026.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-027.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-028.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-029.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-030.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-031.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-032.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-033.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-034.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-035.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-036.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-038.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-039.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-040.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-041.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-042.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-043.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-044.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-045.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-047.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-048.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-050.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-054.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-055.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-056.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-057.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-058.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-059.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-060.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-061.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-062.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-063.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-064.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-065.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-066.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-067.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-068.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-069.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-070.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-072.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-073.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-075.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-076.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-077.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-078.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-079.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-080.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-081.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-082.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-083.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-085.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-086.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-087.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-088.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-089.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-090.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-091.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-093.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-094.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-095.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-097.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-098.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-099.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-100.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-101.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO-102.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BAUTIZO.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BautizoDavid-170.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BautizoDavid-175.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BautizoDavid-268.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/BautizoDavid-285.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BautizoDavid-292.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BautizoDavid-304.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/BautizoDavid-307.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/Bautizo_Aura-042.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/Bautizo_Aura-118.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/Bautizo_Aura-141.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-75.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-76.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-77.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-78.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-79.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-80.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-81.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-82.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-83.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-86.jpg', orientation: 'v'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-87.jpg', orientation: 'h'},
    {src: 'assets/images/bautizos/thumbs/Ede,Hugo & Uriel-88.jpg', orientation: 'v'},
];
